# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'YumemiTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YumemiTask

  # Utility
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'Alamofire-SwiftyJSON'


  # UserInterface
  pod 'FontAwesome.swift'
end
